### ISSUE TITLE
How to remove "shift/bump" from hidden Electron OS X dock icon

### ISSUE THREAD

**Issue by Steveorevo** [segmentio/nightmare#1287]
It's a minor thing but the dock "shifts/bumps" a few pixels when the Electron process enters memory and exits. I thought I'd post this because others might notice or be looking for a workaround. However, the workaround will permanently hide the Electron process icon completely. This "patch" disables the ability to pass the dock/true option (i.e. = Nightmare( {dock:true} ); as it will always be totally hidden (without the annoying "shift/bump"). The solution is to open the Electron.app's plist file in a text editor (i.e. at ./node_modules/nightmare/node_modules/electron/dist/Electron.app/Contents/Info.plist) and append the following between the < dist /> tags at the bottom:

```
<key>NSUIElement</key>
<string>1</string>
```

The process will still be normally visible via Activity Monitor but there will be no dock icon, nor the "shift/bump" (which becomes more obvious if you're doing multiple, several instances or looping). We could consider writing/removing it dynamically using OS X's command line utility:

```
/usr/bin/defaults write Electron.app/Contents/Info "NSUIElement" 1
```

But editing the file directly as a text file seems to work just as easy.

**Comment by matthewmueller** [comment]
Thanks for sharing! Actually it sounds like this could be better resolved in electron. Did you open an issue there too?

**Comment by b-runo** [comment]
Any news about solve this, still happening on MacOS but the instance still in recent dock with electron logo:

```
nightmare({
      electronPath: require('./node_modules/nightmare/node_modules/electron'),
      show: false,
      dock: false
}) 
```
