### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by sapuit** [segmentio/nightmare#725]
Hi everyone, when i run example.js 
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({
	show: true
});
nightmare
	.goto('http://yahoo.com')
	.type('form[action*="/search"] [name=p]', 'github nightmare')
	.click('form[action*="/search"] [type=submit]')
	.wait('#main')
	.evaluate(function() {
		return document.querySelector('#main .searchCenterMiddle li a').href;
	})
	.end()
	.then(function(result) {
		console.log(result);
	})
	.catch(function(error) {
		console.error('Search failed:', error);
	});
```
I have some error : 
```
/Desktop/nodejs/node_modules/nightmare/lib/nightmare.js:77
    debug(`WARNING:  load timeout of ${options.loadTimeout} is shorter than go
          ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Desktop/nodejs/night-mare/exmple.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```
I appreciate any help you can give!

**Comment by rosshinkley** [comment]
Silly question:  what version of Node are you running?

**Comment by sapuit** [comment]
i upgrade the last version , i fixed  it, Thanks a lot!

**Comment by varsano** [comment]
I am having the same problem.
node --version
v0.10.36
But still getting this error.
PLEASE ADVICE

**Comment by rosshinkley** [comment]
@varsano Upgrade NodeJS.  Nightmare will not work with anything <4.x.

**Comment by rxng** [comment]
Hi all, having this issue as well, running the example.js .. what is going on?

node --version
v0.10.46

debug(`WARNING:  load timeout of ${options.loadTimeout} is shorter than go
          ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by varsano** [comment]
Hey,
First of all thanks allot for you answer, it got lost in my tons of emails
and i already managed by my self.
Now that i see you answer i run into a problem when scrapping a webpage:
i scroll to the bottom of the page and every scroll actually triggers a
request with a response and i want to store this response without any luck
screenshot:
[image: Inline images 1]

[image: Inline images 2]



how can i do it?
The page that i am trying to scrap written in AngularJS and i know that the
response that i am looking for i stored somewhere on
*window.self.$scope.ctrl._ads* but i found it only once and it happen after
a several of events that i can't reproduce.

please help since this a really important project that i have to finish in
a couple of days

Thanks allot for your help and great day
